name: Copyright

permissions: write-all

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  copyright-png:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4
      - name: Give copyright script running permissions
        run: chmod +x bin/copyright-pngs.sh
      - name: Run png copyright script
        run: bin/copyright-pngs.sh